services:
  - type: static
    name: mitchell-lagaras.dev
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /
        destination: /index.html
      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /blog
        destination: /blog.html
      - type: rewrite
        source: /contact
        destination: /contact.html
